### ISSUE TITLE
ModuleNotFoundError: No module named 'swn._version'

### ISSUE THREAD

**Issue by izarikos** [mwtoews/surface-water-network#76]
Hi, 

I got this error and I am sure what the solution for this error is.

Cheers,
Ioannis

**Comment by mwtoews** [comment]
Good question, it is related to e241c4a3a1c68ebdee135ea0f9b406f5cf981f23 . I'm guessing you might have installed a development copy via `pip install -e .` once before, so the fix is to re-do that command which automatically generates the `swn/_version.py` file. If that doesn't fix it, then I can provide another solution.
