### ISSUE TITLE
option for original stream_order from shape file?

### ISSUE THREAD

**Issue by wkitlasten** [mwtoews/surface-water-network#77]
It appears stream_order is calculated in recurse_upstream (~ line 373)? This results in different stream_order for the same stream if the network it cropped. Is this optional? If so, where can I set swn to use the original stream_order.

For example, 8th order streams in the Wairua (from DN3) become 6th order streams when I my domain is limited to the main gravel aquifers.

**Comment by mwtoews** [comment]
Since the only input is linework geometry, all other attributes from the original data is ignored. And in the case of a clipped geometry input, it will be incorrect.

One approach is to use [remove()](https://mwtoews.github.io/surface-water-network/ref/swn.SurfaceWaterNetwork.remove.html) on a complete network. But this sometimes requires building a large network, when only a smaller subset is needed.

Another approach (as in this question) is to use the original attributes in a SWN object, which can be simply mapped over. Here is an example that clips linework to stream order 4 or more, creates a new SWN object, then overwrites a few attributes to their correct value.
```python
from pathlib import Path

import geopandas
import numpy as np
import swn

swn_dir = Path(swn.__file__).parent
test_data = swn_dir.parent / "tests" / "data"
assert test_data.exists()

lines_fname = test_data / "DN2_Coastal_strahler1z_stream_vf.shp"

all_lines = geopandas.read_file(lines_fname)
all_lines.set_index("nzsegment", verify_integrity=True, inplace=True)

# Chop a smaller network
xmin, ymin, xmax, ymax = all_lines[all_lines["StreamOrde"] >= 4].total_bounds
xmin, ymin = np.floor([xmin, ymin])
xmax, ymax = np.ceil([xmax, ymax])

lines = all_lines.cx[xmin:xmax, ymin:ymax].geometry

n = swn.SurfaceWaterNetwork.from_lines(lines)

# Copy (and overwrite) segment data from original source
n.segments["stream_order"] = all_lines["StreamOrde"]
n.segments["upstream_area"] = all_lines["CUM_AREA"]
n.segments["sinuosity"] = all_lines["sinuosity"]
```

**Comment by wkitlasten** [comment]
"And in the case of a clipped geometry input, the newly calculated attributes (e.g., upstream_area, stream_order, etc) will be incorrect."
